version: '3.3'

services:
 web:
  build:
   context: .
   dockerfile: ./docker/Dockerfile
  command: gunicorn twobrows.wsgi:application -b 0.0.0.0:8000
  expose:
   - 8000
  depends_on:
   - db
  restart: always
  volumes:
   - .:/code
   - static_volume:/home/app/web/staticfiles
   - media_volume:/home/app/web/mediafiles
  env_file:
   - .env
 db:
  image: postgres:15.6
  container_name: db
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  ports:
   - 5432:5432
  env_file:
   - .env
  restart: always
 nginx:
  restart: unless-stopped
  image: staticfloat/nginx-certbot
  depends_on:
   - web
  ports:
   - "80:80"
   - "443:443"
  environment:
   CERTBOT_EMAIL: kumpan2003@yandex.ru
  volumes:
   - ./docker/nginx/conf/:/etc/nginx/user.conf.d:ro
   - letsencrypt:/etc/letsencrypt
   - static_volume:/home/app/web/staticfiles
   - media_volume:/home/app/web/mediafiles
volumes:
 letsencrypt:
 postgres_data:
 static_volume:
 media_volume: