# Generated by Django 4.2.1 on 2024-08-21 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(verbose_name='Выбирете дату и время')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'records_main',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('photo', models.ImageField(blank=True, upload_to='photos/cards/%Y/%m/%d/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services_main',
                'ordering': ['time_created'],
            },
        ),
    ]
