# Generated by Django 4.2.1 on 2024-08-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Одобрить'),
        ),
    ]
